export default{
  "aovHeroes" : [
    {
      "name" : "Arthur",
      "picture" : "img/arthur.png",
      "role" : ["warrior", "tank"],
      "abilities" : {
        "passive" : "boring passive",
        "s1" : {
          "text" : "runstun",
          "stun": 3,
          "speed" : '30%',
          "dmg" : "boosts next hit's dmg",
          "cd" : 4
        },
        "s2": {
          "text" : "spinny donks",
          "heal" : "1%/s",
          "dmg" : 100,
          "cd" : 5
        },
        "s3" : {
          "text" : "shmash face",
          "heal" : 0,
          "dmg" : 1000,
          "cd" : 8
        }
      },
      "stats" : {
          "hp" : 3800,
          "hpgrow" : 180,
          "admg" : 150,
          "agrow" : 18.2,
          "def" : 150,
          "defgrow" : 18.2
        }
      } 
    ]
  }
      
      
      
      
      
      
      //  figure out how to 
      //  https://pvp.qq.com/
      // https://pvp.qq.com/web201605/herolist.shtml
      // https://pvp.qq.com/web201605/herodetail/166.shtml
      
      // https://www.arenaofvalor.com/web2017/heroDetails.html?id=166

      // https://www.arenaofvalor.com/web2017/herolist.html